---
title: "FSiB - IO"
author: "Hendra Bunyamin"
date: "2024-08-27"
output: html_document
---

# Week 1

## \# Reading/Writing Data in R

## Comma-separated values (CSV)

Kita coba menggunakan library `here`.

```{r}
library(here)

# Make sure we are in the right directory, otherwise we won't find the expected 
# input data file.
##setwd('???')
#setwd("~/Coursera_FSB/Module1_dgc/CODING_WEEK_1")

# Menggunakan library here
here::i_am("3-dataIOCodingLecture.Rmd")

# Read commands have a range of parameters to adjust to the format of the input
# file. I like to visually separate the input to improve readability.

#"~/Coursera_FSB/Module1_dgc/CODING_WEEK_1/DATA/DATA_FSB_SET_1.csv"

data <- read.table(here::here("DATA", "DATA_FSB_SET_1.csv"), 
                   header = TRUE,
                   row.names = 1,
                   sep=',',
                   quote=NULL,
                   skip = 0
                  )
dim(data)

head(data, 5)

# Skip is a useful feature in case data files have header annotations that are 
# not marked by leading comment characters.

# Notice how choosing the wrong separator leads to columns not being split up.
data <- read.table(here::here("DATA", "DATA_FSB_SET_1.csv"), 
                   sep='#'
                  )
dim(data)
head(data)

data

# Shortcut: read.csv is like read.table but with csv presets
data <- read.csv(here::here("DATA", "DATA_FSB_SET_1.csv"),
                 row.names = 1)
dim(data)
head(data)

data


# Writing is equally easy.
outfile <- here::here("DATA", "DATA_SET_TMP.csv")
write.csv(data,
         file = outfile,
         quote = FALSE)

```

## Tab-separated values (TSV)

```{r}
# Separators can be chosen freely, should not occur in the data though.
# Comma and Tab are the most common.
outfile <- here::here("DATA", "DATA_SET_TMP.csv")
write.table(data,
         file = outfile,
         quote = FALSE)

data.reread <- read.table(outfile)
dim(data.reread)
head(data.reread)

outfile <- here::here("DATA", "DATA_SET_TMP.tsv")
write.table(data,sep = "\t",
         file = outfile,
         quote = FALSE)

data.reread <- read.table(outfile)
dim(data.reread)
head(data.reread)
```

## Binary

```{r}
# Let's first save our dataset as binary file.
outfile <-  here::here( "DATA", "DATA_SET_TMP.Rdata" )
save(data, 
     file = outfile)
# Now remove the data object from the work space.
rm(data)

# Loading lets data reappear in the work space.
load(outfile)

# Same with saveRDS.
outfile <- here::here("DATA", "DATA_SET_TMP.Rds" )
saveRDS(object = data, 
     file = outfile)

data.reread <- readRDS(outfile)
dim(data.reread)
```

## Excel

```{r}

# Load Excel IO package
# install.packages("openxlsx")
require(openxlsx)

# Write our data set or list of data to xlsx
outfile <- here::here( "DATA", "DATA_SET_TMP.xlsx"  )
write.xlsx(data, outfile)

# Read our written data back from the Excel file
data.reread <- read.xlsx(outfile)
dim(data.reread)
head(data.reread)
```
